### ISSUE TITLE
Turn editing off

### ISSUE THREAD

**Issue by DNRCJolley71717** [MFreakNL/moodle-local_commander#1]
When selecting the Turn editor off or on, instead of the action being performed, you see the commander/ajax.php page which looks like it's just the json versions of all the commands.

**Comment by luukverhoeven** [comment]
" Turn editor off or on" do you mean on the course page?

![image](https://user-images.githubusercontent.com/995760/42970495-baea58ec-8ba9-11e8-8f37-d96bbfee2b64.png)
