### ISSUE TITLE
Groupings and group overview pages not reachable by the commander

### ISSUE THREAD

**Issue by izendegi** [MFreakNL/moodle-local_commander#15]
Hi,

I've detected that there are two pages of a course group management that are not showing in the commander:
Groupings --> yourmoodlesite/group/groupings.php?id=123456
Group overview -->  yourmoodlesite/group/overview.php?id=123456

**Comment by luukverhoeven** [comment]
@izendegi Thanks for identifying the issue. Are you working with Moodle 4.1 or 4.2? It seems there's a problem with retrieving all the navigation items, as they've been moved to dropdown menus.

**Comment by izendegi** [comment]
Indeed @luukverhoeven , we've detected it on Moodle 4.2

**Comment by luukverhoeven** [comment]
@izendegi, support for this feature has been added in the following branch: https://github.com/LdesignMedia/moodle-local_commander/tree/15-groupings-and-group-overview-pages-not-reachable-by-the-commander.

Could you please check if it functions as expected?

**Comment by izendegi** [comment]
It works like a charm, thank you @luukverhoeven for this great plugin!

**Comment by luukverhoeven** [comment]
@izendegi, thank you for your review. We will merge these changes into the main branch and update the latest version on Moodle.org.
