### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by luukverhoeven** [MFreakNL/moodle-local_commander#16]
Implement a better feature Powerful, lightweight fuzzy-search library, with zero dependencies.
https://www.fusejs.io/

**Comment by leeoniya** [comment]
you might find this useful: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by luukverhoeven** [comment]
@leeoniya Thanks for the suggestion! I will take a look at it.

**Comment by luukverhoeven** [comment]
Solved in 2024101002
