### ISSUE TITLE
Enrolled users & enrolment method pages not reachable by the commander

### ISSUE THREAD

**Issue by izendegi** [MFreakNL/moodle-local_commander#20]
Hi,

I've detected that the pages related with Enrolments and Permissions on a course context are not showing in the commander:

![irudia](https://github.com/user-attachments/assets/49119a02-2113-4def-b503-c67780b3c5fe)

It happens on Moodle 4.4 and happens at least since Moodle 4.1, so it seems it can be related with #15, which solved the group related pages listed on the same menu.

**Comment by luukverhoeven** [comment]
@hamzatamyachte If you have a moment, can you take a look at this issue? Thanks

**Comment by luukverhoeven** [comment]
@hamzatamyachte Thanks for the update.

**Comment by izendegi** [comment]
It works like a charm, thank you!
