### ISSUE TITLE
Can't get it to work for editingteacher

### ISSUE THREAD

**Issue by lucaboesch** [MFreakNL/moodle-local_commander#4]
Dear Luuk

Unlike what you write in the docs: Available for 'manager', 'coursecreator', 'editingteacher', 'teacher', I can't get it to work for editingteacher. Moodle stable checked out.
Admin: working beautifully, Teacher: not appearing.

Your Behat test then also tests it as admin.
Can you provide some proof it works for editingteacher, too?

**Comment by luukverhoeven** [comment]
Dear Luca,

Thanks for checking this. There was a problem with the capability check. I fixed the issue and updated the version on moodle.org

There is now also a behat test for the teacher role.

https://moodle.org/plugins/pluginversion.php?id=19471

**Comment by lucaboesch** [comment]
That's brilliant, Luuk!

Many thanks,
Luca
