### ISSUE TITLE
Do not fire if you are inside of a textarea, input, or select

### ISSUE THREAD

**Issue by lucaboesch** [MFreakNL/moodle-local_commander#5]
Maybe it could be possible to assure that the hotkey does not fire if you are inside of a textarea, input, or select.

This submission to plugin directory does this: 
https://github.com/samber/moodle-local_keyboard_shortcuts

Best,
Luca

**Comment by luukverhoeven** [comment]
Hi Luca, 

Thanks for the comment. I added support for this in the new version of the plugin 
https://github.com/MFreakNL/moodle-local_commander/releases/tag/3.8.1

**Comment by lucaboesch** [comment]
Thanks a lot, Luuk.
Fireing of the modal menu is prevented, sure. That's great!
It seems, though, that the glyph that you were intended to write, gets silently dropped.
Would it be possible to write it normally when inside of a textarea, input, or select?
You may have to set that to a standard key = a | code = 65 to develop/reproduce.
Best,
Luca

**Comment by luukverhoeven** [comment]
Thanks Luca for the feedback, this issue should be solved now.
